# vim: fixeol eol expandtab tabstop=2 shiftwidth=2
{ pkgs, config, util, lib, ... }: {
  xdg.configFile."mimeapps.list".force = true; # This keeps getting overwritten for some reason
  xdg.mimeApps = {
    enable = true;
    defaultApplicationPackages = with pkgs; [ nemo-fileroller file-roller ];
    defaultApplications = (x:
      util.merge (util.merge (builtins.attrValues (builtins.mapAttrs
        (program: filetypes:
          (builtins.map (filetype: { ${filetype} = [ "${program}.desktop" ]; })
            filetypes)) x)))) {
              zen-browser = [
                "text/html"
                "x-scheme-handler/http"
                "x-scheme-handler/https"
                "x-scheme-handler/about"
                "x-scheme-handler/mailto"
                "x-scheme-handler/unknown"
              ];
              qpdfview = [
                "application/pdf"
                "application/x-pdf"
                "text/pdf"
                "text/x-pdf"
                "image/pdf"
                "image/x-pdf"
                "application/postscript"
                "image/vnd.djvu"
                "image/x-djvu"
              ];
              nemo = [ "inode/directory" "application/x-gnome-saved-search" ];
              nvim = [
                "text/english"
                "text/plain"
                "text/x-makefile"
                "text/x-c++hdr"
                "text/x-c++src"
                "text/x-chdr"
                "text/x-csrc"
                "text/x-java"
                "text/x-moc"
                "text/x-pascal"
                "text/x-tcl"
                "text/x-tex"
                "application/x-shellscript"
                "text/x-c"
                "text/x-c++"
                "application/json"
              ];
              # https://stackoverflow.com/a/4212908
              writer = builtins.map (x: "application/${x}") [
                "clarisworks"
                "docbook+xml"
                "macwriteii"
                "msword"
                "prs.plucker"
                "rtf"
                "vnd.apple.pages"
                "vnd.lotus-wordpro"
                "vnd.ms-word"
                "vnd.ms-word.document.macroEnabled.12"
                "vnd.ms-word.template.macroEnabled.12"
                "vnd.ms-works"
                "vnd.oasis.opendocument.text"
                "vnd.oasis.opendocument.text-flat-xml"
                "vnd.oasis.opendocument.text-master"
                "vnd.oasis.opendocument.text-master-template"
                "vnd.oasis.opendocument.text-template"
                "vnd.oasis.opendocument.text-web"
                "vnd.openxmlformats-officedocument.wordprocessingml.document"
                "vnd.openxmlformats-officedocument.wordprocessingml.template"
                "vnd.palm"
                "vnd.stardivision.writer-global"
                "vnd.stardivision.writer-global"
                "vnd.sun.xml.writer"
                "vnd.sun.xml.writer.global"
                "vnd.sun.xml.writer.template"
                "vnd.wordperfect"
                "wordperfect"
                "x-abiword"
                "x-aportisdoc"
                "x-doc"
                "x-extension-txt"
                "x-fictionbook+xml"
                "x-hwp"
                "x-iwork-pages-sffpages"
                "x-mswrite"
                "x-pocket-word"
                "x-sony-bbeb"
                "x-starwriter"
                "x-starwriter-global"
                "x-t602"
              ];
              impress = builtins.map (x: "application/${x}") [
                "mspowerpoint"
                "vnd.apple.keynote"
                "vnd.ms-powerpoint"
                "vnd.ms-powerpoint.presentation.macroEnabled.12"
                "vnd.ms-powerpoint.slideshow.macroEnabled.12"
                "vnd.ms-powerpoint.template.macroEnabled.12"
                "vnd.oasis.opendocument.presentation"
                "vnd.oasis.opendocument.presentation-flat-xml"
                "vnd.oasis.opendocument.presentation-template"
                "vnd.openxmlformats-officedocument.presentationml.presentation"
                "vnd.openxmlformats-officedocument.presentationml.slide"
                "vnd.openxmlformats-officedocument.presentationml.slideshow"
                "vnd.openxmlformats-officedocument.presentationml.template"
                "vnd.stardivision.impress"
                "vnd.sun.xml.impress"
                "vnd.sun.xml.impress.template"
                "x-iwork-keynote-sffkey"
                "x-starimpress"
              ];
              # "calc is short for calculator, chat"
              calc = builtins.map (x: "application/${x}") [
                "clarisworks"
                "csv"
                "excel"
                "msexcel"
                "tab-separated-values"
                "vnd.apache.parquet"
                "vnd.apple.numbers"
                "vnd.lotus-1-2-3"
                "vnd.ms-excel"
                "vnd.ms-excel.sheet.binary.macroEnabled.12"
                "vnd.ms-excel.sheet.macroEnabled.12"
                "vnd.ms-excel.template.macroEnabled.12"
                "vnd.ms-works"
                "vnd.oasis.opendocument.chart"
                "vnd.oasis.opendocument.chart-template"
                "vnd.oasis.opendocument.spreadsheet"
                "vnd.oasis.opendocument.spreadsheet-flat-xml"
                "vnd.oasis.opendocument.spreadsheet-template"
                "vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                "vnd.openxmlformats-officedocument.spreadsheetml.template"
                "vnd.stardivision.calc"
                "vnd.stardivision.chart"
                "vnd.sun.xml.calc"
                "vnd.sun.xml.calc.template"
                "x-123"
                "x-dbase"
                "x-dbf"
                "x-dos_ms_excel"
                "x-excel"
                "x-gnumeric"
                "x-iwork-numbers-sffnumbers"
                "x-ms-excel"
                "x-msexcel"
                "x-quattropro"
                "x-starcalc"
                "x-starchart"
              ] ++ [
                "text/comma-separated-values"
                "text/csv"
                "text/spreadsheet"
                "text/tab-separated-values"
                "text/x-comma-separated-values"
                "text/x-csv"
              ];
              math = builtins.map (x: "application/${x}") [
                "mathml+xml"
                "vnd.oasis.opendocument.formula"
                "vnd.oasis.opendocument.formula-template"
                "vnd.stardivision.math"
                "vnd.sun.xml.math"
                "x-starmath"
              ] ++ [ "text/mathml" ];
              draw = builtins.map (x: "application/${x}") [
                "clarisworks"
                "pdf"
                "vnd.corel-draw"
                "vnd.ms-publisher"
                "vnd.oasis.opendocument.graphics"
                "vnd.oasis.opendocument.graphics-flat-xml"
                "vnd.oasis.opendocument.graphics-template"
                "vnd.quark.quarkxpress"
                "vnd.stardivision.draw"
                "vnd.sun.xml.draw"
                "vnd.sun.xml.draw.template"
                "vnd.visio"
                "x-pagemaker"
                "x-stardraw"
                "x-wpg"
              ] ++ [ "image/x-emf" "image/x-freehand" "image/x-wmf" ];
              base = [
                "application/vnd.oasis.opendocument.base"
                "application/vnd.sun.xml.base"
              ];
            };
  };
}
