# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/de4993a9-6bc8-4d92-8e8e-e5536cc716ef";
    fsType = "btrfs";
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/de4993a9-6bc8-4d92-8e8e-e5536cc716ef";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/26BA-881F";
    fsType = "vfat";
    options = [
      "fmask=0133"
      "dmask=0022"
    ];
  };

  fileSystems."/artix" = {
    device = "/dev/disk/by-uuid/f47ca19a-8c8c-40dd-b0d3-9b710204bb3a";
    fsType = "btrfs";
  };

  fileSystems."/storage" = {
    device = "/dev/disk/by-uuid/92260c94-eb0a-4ac5-a06d-e149d80b7f46";
    fsType = "ext4";
  };

  fileSystems."/artix/boot" = {
    device = "/dev/disk/by-uuid/E8D8-8E67";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
